name: Automation tests for magento.softwaretestingboard.com

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - smoke_test
          - regression_test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: your/repository
          ref: ${{ github.event.inputs.deployment_target }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: smoke_test
        if: "github.event.inputs.deployment_target == 'smoke_test'"
        run: pytest -s -v -m smoke
      - name: regression_test
        if: "github.event.inputs.deployment_target == 'regression_test'"
        run: pytest -s -v

