name: Automation tests for magento.softwaretestingboard.com

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: smoke_test
        type: choice
        options:
          - smoke_test
          - regression_test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: smoke_test
        if: "github.event.inputs.deployment_target == 'smoke_test'"
        run: pytest -s -v -m smoke
      - name: regression_test
        if: "github.event.inputs.deployment_target == 'regression_test'"
        run: pytest -s -v
      - name: Save screenshots as artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ${{ github.event.inputs.deployment_target }}.png

